import type { ImageSourcePropType } from "react-native";

import type { Review, Therapist, TherapistDetail } from "./therapists/types";

export { getOptionLabel, locationOptions, specializationOptions } from "./therapists/options";
export type { Review, Therapist, TherapistDetail } from "./therapists/types";

const therapistPhotos: Record<string, ImageSourcePropType> = {
  "1": require("../assets/images/therapists/dr-david-wairoto.jpg"),
  "2": require("../assets/images/therapists/dr-neema-araka.jpg"),
  "3": require("../assets/images/therapists/Dr-J-M-MNdegwa-MBS.jpg"),
  "4": require("../assets/images/therapists/Dr-Rajab-Saddam.jpg"),
  "5": require("../assets/images/therapists/Dr-Susan-Wangeci-Kuria.jpg"),
  "6": require("../assets/images/therapists/Therapists-image.jpg"),
  "7": require("../assets/images/therapists/Therapists-image.jpg"),
  "8": require("../assets/images/therapists/Dr.-Kingi-Mochache-Vicechair.jpg"),
  "9": require("../assets/images/therapists/Therapists-image.jpg"),
  "10": require("../assets/images/therapists/dr--jackline-ochieng.jpg"),
  "11": require("../assets/images/therapists/Dr-Catherine-Munanie.jpg"),
  "12": require("../assets/images/therapists/dr-samuel-kamoche.webp"),
  "13": require("../assets/images/therapists/dr-lina-akello.jpg"),
  "14": require("../assets/images/therapists/Therapists-image.jpg"),
  "15": require("../assets/images/therapists/oasis-doctors-plaza-eldoret.jpg"),
  "16": require("../assets/images/therapists/Dr-Kevin-Wamula.jpg"),
  "17": require("../assets/images/therapists/Dr.-Erica-Adagala.jpeg"),
  "18": require("../assets/images/therapists/dr-linda-n-nyamute.jpg"),
  "19": require("../assets/images/therapists/Oasis-kisii-branch.jpeg"),
  "20": require("../assets/images/therapists/Consolata-Mathari-Hospital.png"),
  "21": require("../assets/images/therapists/nyeri-county-referral-hospital.jpeg"),
};

export const mockTherapists: Therapist[] = [
  {
    id: "1",
    name: "Dr. David Kagwi Wairoto",
    photo: therapistPhotos["1"],
    location: "Chiromo Lane Doctors Plaza, Muthangari Road, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 745 113 866",
    email: "info@neurowellnessclinic.co.ke",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Depression",
      "Stress Management",
      "Anxiety",
    ],
    bio: "Consultant Psychiatrist focusing on adult mental health including depression, stress, anxiety, and related conditions.",
  },
  {
    id: "2",
    name: "Dr. Neema Araka",
    photo: therapistPhotos["2"],
    location: "FITAHI CONSULTANCY CLINIC, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0704 453 316",
    email: "fitahi254@gmail.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Stress Management",
      "Anger Management",
      "Sleep / Insomnia",
      "Anxiety",
      "Grief & Loss",
      "Self-Esteem",
      "Emotion Regulation",
    ],
    bio: "Psychiatrist specializing in preventive and promotive mental health, psychotherapy, and resilience-building.",
  },
  {
    id: "3",
    name: "Dr. J M M'Ndegwa 'MBS'",
    photo: therapistPhotos["3"],
    location:
      "Integrated Clinical Services (NICS), Nairobi (P.O. Box 22486-00400)",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 769 075 962",
    email: "ndegwa@nics.co.ke",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Addiction", "Trauma"],
    bio: "Consultant Psychiatrist with special interest in addiction medicine, psychotrauma, and adult psychiatry.",
  },
  {
    id: "4",
    name: "Dr. Rajab Saddam",
    photo: therapistPhotos["4"],
    location:
      "UpperHill Medical Center / H.S Medical Centre (KNH affiliated), Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 113 799 016",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Depression", "Anxiety"],
    bio: "Consultant Psychiatrist specializing in adult psychiatry, providing consultations for a range of mental health concerns.",
  },
  {
    id: "5",
    name: "Dr. Susan Wangeci Kuria",
    photo: therapistPhotos["5"],
    location: "Mathari National Teaching and Referral Hospital, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 751 180 101",
    email: "mental.health.care.swk@gmail.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist at Mathari National Teaching and Referral Hospital with expertise in adult psychiatry and complex psychiatric care.",
  },
  {
    id: "6",
    name: "Dr. Margaret Othieno Makanyengo",
    photo: therapistPhotos["6"],
    location: "Greenhouse Mall, Ngong Road, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 782 829 509",
    email: "info@oasishealthcaregroup.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "HIV Psychiatry", "Trauma"],
    bio: "Consultant Psychiatrist with 21+ years of experience, known for pioneering HIV psychiatry and gender-based violence services.",
  },
  {
    id: "7",
    name: "Dr. Susan Hinga",
    photo: therapistPhotos["7"],
    location: "Mater Hospital, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 711 328 181",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist at Mater Hospital focusing on general adult psychiatry and compassionate mental health treatment.",
  },
  {
    id: "8",
    name: "Dr. Kingi K Mochache",
    photo: therapistPhotos["8"],
    location: "Fortis Suites, Upperhill, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 741 668 020",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist running a specialist clinic, providing general psychiatric care and medication management.",
  },
  {
    id: "9",
    name: "Dr. Pauline Ng'ang'a",
    photo: therapistPhotos["9"],
    location:
      "University of Nairobi Dept of Psychiatry / Chiromo Hospital Group, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0115 876 000",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Consultant Psychiatrist dual-trained in clinical psychology and psychiatry, providing integrated psychological and medical care.",
  },
  {
    id: "10",
    name: "Dr. Jackline Ochieng'",
    photo: therapistPhotos["10"],
    location: "Menelik Medical Centre, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 720 291 232",
    email: "frontdesk@gileadmh.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Specialist Psychiatrist providing general adult psychiatric care including diagnosis, treatment, and ongoing support.",
  },
  {
    id: "11",
    name: "Dr. Catherine Munanie Syengo Mutisya",
    photo: therapistPhotos["11"],
    location: "KMA Centre, Upper Hill, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0202 365 638",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Family Therapy"],
    bio: "Consultant Psychiatrist with extensive clinical and leadership experience, focusing on general psychiatry and family therapy.",
  },
  {
    id: "12",
    name: "Dr. Samuel Kamoche",
    photo: therapistPhotos["12"],
    location: "Laric Heart Centre, near Quickmart, Kakamega",
    county: "Kakamega County",
    town: "Kakamega",
    phone: "+254 714 965 619",
    whatsapp: "+254 714 965 619",
    coords: { lat: 0.2827, lng: 34.7519 },
    specialization: [
      "Psychiatry",
      "Addiction",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Psychiatrist treating adults and children across Western Kenya, supporting a range of mental health conditions.",
  },
  {
    id: "13",
    name: "Dr. Lina Akello",
    photo: therapistPhotos["13"],
    location: "Oasis Doctor Plaza, Kakamega (also Aga Khan Kisumu)",
    county: "Kakamega County",
    town: "Kakamega",
    phone: "+254 710 292 903",
    coords: { lat: 0.2827, lng: 34.7519 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist providing general psychiatric services across Western Kenya and Kisumu facilities.",
  },
  {
    id: "14",
    name: "Dr. Daniel Waiganjo Kinyanjui",
    photo: therapistPhotos["14"],
    location: "Eldoret",
    county: "Uasin Gishu County",
    town: "Eldoret",
    phone: "0774 248 196",
    coords: { lat: 0.5143, lng: 35.2698 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist providing general psychiatric services in Eldoret.",
  },
  {
    id: "15",
    name: "Oasis Doctors Plaza Eldoret (Psychology & Psychiatry dept)",
    photo: therapistPhotos["15"],
    location: "Oasis Doctors Plaza, Eldoret",
    county: "Uasin Gishu County",
    town: "Eldoret",
    phone: "0111 161 400",
    email: "info@oasishealthcaregroup.com",
    coords: { lat: 0.5143, lng: 35.2698 },
    specialization: ["Psychiatry"],
    bio: "Psychology and psychiatry services available through Oasis Healthcare Group in Eldoret.",
  },
  {
    id: "16",
    name: "Dr. Kevin Wamula",
    photo: therapistPhotos["16"],
    location: "Pandya Hospital, Dedan Kimathi Avenue, Mombasa",
    county: "Mombasa County",
    town: "Mombasa",
    phone: "+254 734 600 663",
    coords: { lat: -4.043477, lng: 39.668206 },
    specialization: ["Psychiatry", "Depression"],
    bio: "Psychiatrist at Pandya Hospital with interests including treatment-resistant depression, ketamine therapy, and general mental health care.",
  },
  {
    id: "17",
    name: "Dr. Erica Adagala",
    photo: therapistPhotos["17"],
    location: "AFC House Building, Nakuru",
    county: "Nakuru County",
    town: "Nakuru",
    phone: "+254 713 046 424",
    email: "pristonhealthcareltd@gmail.com",
    coords: { lat: -0.3031, lng: 36.08 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "KPA Consultant Psychiatrist offering general psychiatric care in Nakuru.",
  },
  {
    id: "18",
    name: "Dr. Linda N. Nyamute",
    photo: therapistPhotos["18"],
    location:
      "Jaramogi Oginga Odinga Teaching & Referral Hospital (Kisumu area)",
    county: "Kisumu County",
    town: "Kisumu",
    phone: "0737 879 077",
    email: "mentalsphereke@gmail.com",
    coords: { lat: -0.091702, lng: 34.767956 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist focused on general adult psychiatry and community mental health in the Kisumu region.",
  },
  {
    id: "19",
    name: "Oasis Branches (Kisii Hospital & Siaya Hospital)",
    photo: therapistPhotos["19"],
    location: "Oasis Healthcare Group branches (Kisii & Siaya)",
    county: "Kisii County / Siaya County",
    town: "Kisii / Siaya",
    phone: "0111 161 400",
    coords: { lat: -0.091702, lng: 34.767956 },
    specialization: ["Psychiatry"],
    bio: "Psychiatry services available through Oasis Healthcare Group branches in Kisii and Siaya.",
  },
  {
    id: "20",
    name: "Consolata Mathari Hospital Psychiatric Clinic (Nyeri)",
    photo: therapistPhotos["20"],
    location: "Consolata Mathari Hospital, Nyeri",
    county: "Nyeri County",
    town: "Nyeri",
    phone: "+254 721 358 137",
    coords: { lat: -0.4197, lng: 36.9511 },
    specialization: ["Psychiatry"],
    bio: "Psychiatric clinic in Nyeri offering mental health support through Consolata Mathari Hospital.",
  },
  {
    id: "21",
    name: "Nyeri County Referral Hospital Mental Health Outpatient",
    photo: therapistPhotos["21"],
    location: "Nyeri County Referral Hospital, Nyeri",
    county: "Nyeri County",
    town: "Nyeri",
    phone: "0724 249 693",
    coords: { lat: -0.4197, lng: 36.9511 },
    specialization: ["Psychiatry"],
    bio: "Mental health outpatient services at Nyeri County Referral Hospital.",
  },
];

const mockTherapistDetails: Record<string, TherapistDetail> = {
  "1": {
    id: "1",
    name: "Dr. David Kagwi Wairoto",
    photo: therapistPhotos["1"],
    location: "Chiromo Lane Doctors Plaza, Muthangari Road, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 745 113 866",
    email: "info@neurowellnessclinic.co.ke",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Depression",
      "Stress Management",
      "Anxiety",
    ],
    bio: "Consultant Psychiatrist focusing on adult mental health including depression, stress, anxiety, and related conditions.",
    fullBio:
      "Consultant Psychiatrist with qualifications including MBChB and MMed Psychiatry (University of Nairobi), plus AIMIS (Strathmore). Runs Neuro Wellness Clinic, focusing on general adult psychiatry including depression, stress, anxiety, and related conditions.",
    qualifications: [
      "MBChB",
      "MMed Psychiatry (University of Nairobi)",
      "AIMIS (Strathmore)",
    ],
    experience: "",
  },
  "2": {
    id: "2",
    name: "Dr. Neema Araka",
    photo: therapistPhotos["2"],
    location: "FITAHI CONSULTANCY CLINIC, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0704 453 316",
    email: "fitahi254@gmail.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Stress Management",
      "Anger Management",
      "Sleep / Insomnia",
      "Anxiety",
      "Grief & Loss",
      "Self-Esteem",
      "Emotion Regulation",
    ],
    bio: "Psychiatrist specializing in preventive and promotive mental health, psychotherapy, and resilience-building.",
    fullBio:
      "Psychiatrist at FITAHI CONSULTANCY CLINIC specializing in preventive and promotive mental health. Expertise in behavioral therapy, psychotherapy, stress & anger management, insomnia, self-esteem issues, social anxiety, emotion regulation, grief, loss, and loneliness.",
    qualifications: [],
    experience: "",
  },
  "3": {
    id: "3",
    name: "Dr. J M M'Ndegwa 'MBS'",
    photo: therapistPhotos["3"],
    location:
      "Integrated Clinical Services (NICS), Nairobi (P.O. Box 22486-00400)",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 769 075 962",
    email: "ndegwa@nics.co.ke",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Addiction", "Trauma"],
    bio: "Consultant Psychiatrist with special interest in addiction medicine, psychotrauma, and adult psychiatry.",
    fullBio:
      "Consultant Psychiatrist (also known as Dr. Japheth Mwenda M'Ndegwa) with special interest in addiction medicine, psychotrauma, and adult psychiatry. Practices at Integrated Clinical Services (NICS).",
    qualifications: [],
    experience: "",
  },
  "4": {
    id: "4",
    name: "Dr. Rajab Saddam",
    photo: therapistPhotos["4"],
    location:
      "UpperHill Medical Center / H.S Medical Centre (KNH affiliated), Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 113 799 016",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Depression", "Anxiety"],
    bio: "Consultant Psychiatrist specializing in adult psychiatry.",
    fullBio:
      "Consultant Psychiatrist specializing in adult psychiatry. Works at UpperHill Medical Center / H.S Medical Centre and is affiliated with Kenyatta National Hospital.",
    qualifications: [],
    experience: "",
  },
  "5": {
    id: "5",
    name: "Dr. Susan Wangeci Kuria",
    photo: therapistPhotos["5"],
    location: "Mathari National Teaching and Referral Hospital, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 751 180 101",
    email: "mental.health.care.swk@gmail.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist at Mathari National Teaching and Referral Hospital with expertise in adult psychiatry.",
    fullBio:
      "Consultant Psychiatrist at Mathari National Teaching and Referral Hospital, with expertise in adult psychiatry. Experienced in clinical care, research, and managing complex psychiatric conditions.",
    qualifications: [],
    experience: "",
  },
  "6": {
    id: "6",
    name: "Dr. Margaret Othieno Makanyengo",
    photo: therapistPhotos["6"],
    location: "Greenhouse Mall, Ngong Road, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 782 829 509",
    email: "info@oasishealthcaregroup.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "HIV Psychiatry", "Trauma"],
    bio: "Consultant Psychiatrist with 21+ years of experience, formerly at Kenyatta National Hospital.",
    fullBio:
      "Esteemed Consultant Psychiatrist with over 21 years of experience (formerly at Kenyatta National Hospital, where she pioneered HIV psychiatry and gender-based violence services). Now at Oasis Healthcare Group, providing specialized care for HIV-related issues, trauma, and general psychiatry.",
    qualifications: [],
    experience: "21+ years",
  },
  "7": {
    id: "7",
    name: "Dr. Susan Hinga",
    photo: therapistPhotos["7"],
    location: "Mater Hospital, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 711 328 181",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist at Mater Hospital focusing on general adult psychiatry.",
    fullBio:
      "Psychiatrist at Mater Hospital with qualifications from Makerere (MBChB) and University of Nairobi (MMed Psychiatry). Focuses on general adult psychiatry.",
    qualifications: [
      "MBChB (Makerere)",
      "MMed Psychiatry (University of Nairobi)",
    ],
    experience: "",
  },
  "8": {
    id: "8",
    name: "Dr. Kingi K Mochache",
    photo: therapistPhotos["8"],
    location: "Fortis Suites, Upperhill, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 741 668 020",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist providing general psychiatric care and medication management.",
    fullBio:
      "Consultant Psychiatrist (MBChB 2007, MMed Psychiatry 2016 from University of Nairobi) running a specialist psychiatry clinic and providing general psychiatric care.",
    qualifications: [
      "MBChB (2007)",
      "MMed Psychiatry (University of Nairobi, 2016)",
    ],
    experience: "",
  },
  "9": {
    id: "9",
    name: "Dr. Pauline Ng'ang'a",
    photo: therapistPhotos["9"],
    location:
      "University of Nairobi Dept of Psychiatry / Chiromo Hospital Group, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0115 876 000",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Dual-trained in clinical psychology and psychiatry, providing integrated care.",
    fullBio:
      "Consultant Psychiatrist at Chiromo Hospital Group (also affiliated with University of Nairobi Department of Psychiatry). Dual-trained in clinical psychology and psychiatry (MBChB, MSc Clin. Psy, MMed Psych) and handles a broad range of mental health issues.",
    qualifications: ["MBChB", "MSc Clinical Psychology", "MMed Psychiatry"],
    experience: "",
  },
  "10": {
    id: "10",
    name: "Dr. Jackline Ochieng'",
    photo: therapistPhotos["10"],
    location: "Menelik Medical Centre, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "+254 720 291 232",
    email: "frontdesk@gileadmh.com",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Specialist Psychiatrist providing diagnosis, treatment, and support for general mental health concerns.",
    fullBio:
      "Specialist Psychiatrist at Gilead Mental Health Consultants / Menelik Medical Centre (MBChB Makerere, MMed Psychiatry Nairobi). Provides general psychiatric care, focusing on diagnosis, treatment, and support for adults.",
    qualifications: [
      "MBChB (Makerere)",
      "MMed Psychiatry (University of Nairobi)",
    ],
    experience: "",
  },
  "11": {
    id: "11",
    name: "Dr. Catherine Munanie Syengo Mutisya",
    photo: therapistPhotos["11"],
    location: "KMA Centre, Upper Hill, Nairobi",
    county: "Nairobi County",
    town: "Nairobi",
    phone: "0202 365 638",
    coords: { lat: -1.286389, lng: 36.817223 },
    specialization: ["Psychiatry", "Family Therapy"],
    bio: "Consultant Psychiatrist specializing in general psychiatry, family therapy, and mental health service leadership.",
    fullBio:
      "Consultant Psychiatrist (MBChB and MMed Psychiatry from University of Nairobi) with extensive experience in leadership, advocacy, and clinical practice. Specializes in general psychiatry and family therapy.",
    qualifications: ["MBChB", "MMed Psychiatry (University of Nairobi)"],
    experience: "",
  },
  "12": {
    id: "12",
    name: "Dr. Samuel Kamoche",
    photo: therapistPhotos["12"],
    location: "Laric Heart Centre, near Quickmart, Kakamega",
    county: "Kakamega County",
    town: "Kakamega",
    phone: "+254 714 965 619",
    whatsapp: "+254 714 965 619",
    coords: { lat: 0.2827, lng: 34.7519 },
    specialization: [
      "Psychiatry",
      "Addiction",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "Psychiatrist treating adults and children with a focus that includes addiction, stress, depression, and anxiety.",
    fullBio:
      "Psychiatrist treating adults and children in Western Kenya (Laric Heart Centre, Kakamega). Serves Kakamega, Bungoma, Busia, Kitale, and Vihiga.",
    qualifications: [],
    experience: "",
  },
  "13": {
    id: "13",
    name: "Dr. Lina Akello",
    photo: therapistPhotos["13"],
    location: "Oasis Doctor Plaza, Kakamega (also Aga Khan Kisumu)",
    county: "Kakamega County",
    town: "Kakamega",
    phone: "+254 710 292 903",
    coords: { lat: 0.2827, lng: 34.7519 },
    specialization: ["Psychiatry"],
    bio: "Consultant Psychiatrist providing general psychiatric services across Western Kenya and Kisumu.",
    fullBio:
      "Consultant Psychiatrist providing general psychiatric services across Oasis and Aga Khan facilities in Western Kenya and Kisumu.",
    qualifications: [],
    experience: "",
  },
  "14": {
    id: "14",
    name: "Dr. Daniel Waiganjo Kinyanjui",
    photo: therapistPhotos["14"],
    location: "Eldoret",
    county: "Uasin Gishu County",
    town: "Eldoret",
    phone: "0774 248 196",
    coords: { lat: 0.5143, lng: 35.2698 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist providing general psychiatric services in Eldoret.",
    fullBio:
      "Psychiatrist based in Eldoret providing psychiatric consultations and care.",
    qualifications: [],
    experience: "",
  },
  "15": {
    id: "15",
    name: "Oasis Doctors Plaza Eldoret (Psychology & Psychiatry dept)",
    photo: therapistPhotos["15"],
    location: "Oasis Doctors Plaza, Eldoret",
    county: "Uasin Gishu County",
    town: "Eldoret",
    phone: "0111 161 400",
    email: "info@oasishealthcaregroup.com",
    coords: { lat: 0.5143, lng: 35.2698 },
    specialization: ["Psychiatry"],
    bio: "Psychology and psychiatry services available through Oasis Healthcare Group in Eldoret.",
    fullBio:
      "Oasis Doctors Plaza Eldoret offers psychology and psychiatry services. Contact the facility for appointments and service availability.",
    qualifications: [],
    experience: "",
  },
  "16": {
    id: "16",
    name: "Dr. Kevin Wamula",
    photo: therapistPhotos["16"],
    location: "Pandya Hospital, Dedan Kimathi Avenue, Mombasa",
    county: "Mombasa County",
    town: "Mombasa",
    phone: "+254 734 600 663",
    coords: { lat: -4.043477, lng: 39.668206 },
    specialization: ["Psychiatry", "Depression"],
    bio: "Psychiatrist at Pandya Hospital with interests including treatment-resistant depression and ketamine therapy.",
    fullBio:
      "Psychiatrist at Pandya Hospital (Mombasa) specializing in treatment-resistant depression, ketamine therapy, and general mental health concerns.",
    qualifications: [],
    experience: "",
  },
  "17": {
    id: "17",
    name: "Dr. Erica Adagala",
    photo: therapistPhotos["17"],
    location: "AFC House Building, Nakuru",
    county: "Nakuru County",
    town: "Nakuru",
    phone: "+254 713 046 424",
    email: "pristonhealthcareltd@gmail.com",
    coords: { lat: -0.3031, lng: 36.08 },
    specialization: [
      "Psychiatry",
      "Stress Management",
      "Depression",
      "Anxiety",
    ],
    bio: "KPA Consultant Psychiatrist offering general psychiatric care in Nakuru.",
    fullBio:
      "KPA Consultant Psychiatrist offering general psychiatric care, including stress, depression, and anxiety management in Nakuru.",
    qualifications: [],
    experience: "",
  },
  "18": {
    id: "18",
    name: "Dr. Linda N. Nyamute",
    photo: therapistPhotos["18"],
    location:
      "Jaramogi Oginga Odinga Teaching & Referral Hospital (Kisumu area)",
    county: "Kisumu County",
    town: "Kisumu",
    phone: "0737 879 077",
    email: "mentalsphereke@gmail.com",
    coords: { lat: -0.091702, lng: 34.767956 },
    specialization: ["Psychiatry"],
    bio: "Psychiatrist focused on general adult psychiatry and community mental health.",
    fullBio:
      "Psychiatrist at Jaramogi Oginga Odinga Teaching & Referral Hospital (Kisumu area), focused on general adult psychiatry and community mental health.",
    qualifications: [],
    experience: "",
  },
  "19": {
    id: "19",
    name: "Oasis Branches (Kisii Hospital & Siaya Hospital)",
    photo: therapistPhotos["19"],
    location: "Oasis Healthcare Group branches (Kisii & Siaya)",
    county: "Kisii County / Siaya County",
    town: "Kisii / Siaya",
    phone: "0111 161 400",
    coords: { lat: -0.091702, lng: 34.767956 },
    specialization: ["Psychiatry"],
    bio: "Psychiatry services available through Oasis Healthcare Group branches in Kisii and Siaya.",
    fullBio:
      "Oasis Healthcare Group provides psychiatry services via its Kisii and Siaya branches. Contact the facility to confirm clinician availability.",
    qualifications: [],
    experience: "",
  },
  "20": {
    id: "20",
    name: "Consolata Mathari Hospital Psychiatric Clinic (Nyeri)",
    photo: therapistPhotos["20"],
    location: "Consolata Mathari Hospital, Nyeri",
    county: "Nyeri County",
    town: "Nyeri",
    phone: "+254 721 358 137",
    coords: { lat: -0.4197, lng: 36.9511 },
    specialization: ["Psychiatry"],
    bio: "Psychiatric clinic in Nyeri offering mental health support.",
    fullBio:
      "Consolata Mathari Hospital Psychiatric Clinic provides mental health services in Nyeri. An additional contact number provided is +254 702 697 344.",
    qualifications: [],
    experience: "",
  },
  "21": {
    id: "21",
    name: "Nyeri County Referral Hospital Mental Health Outpatient",
    photo: therapistPhotos["21"],
    location: "Nyeri County Referral Hospital, Nyeri",
    county: "Nyeri County",
    town: "Nyeri",
    phone: "0724 249 693",
    coords: { lat: -0.4197, lng: 36.9511 },
    specialization: ["Psychiatry"],
    bio: "Mental health outpatient services at Nyeri County Referral Hospital.",
    fullBio:
      "Nyeri County Referral Hospital provides mental health outpatient services. Contact the facility for appointment details.",
    qualifications: [],
    experience: "",
  },
};

export const mockReviews: Review[] = [];

export function getTherapistById(id: string | undefined | null) {
  if (!id) return undefined;
  return mockTherapistDetails[id];
}
