# Generated by Django 5.1.15 on 2025-12-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
