# Generated by Django 5.1.15 on 2025-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doctor_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insuarance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='insuarance',
            field=models.ManyToManyField(blank=True, related_name='insuarance', to='core.insuarance'),
        ),
    ]
