# Generated by Django 5.1.15 on 2025-12-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_country_doctor_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='Start of the 30-minute availability slot')),
                ('end_time', models.DateTimeField(help_text='End of the slot (start_time + 30 minutes)')),
                ('is_recurring', models.BooleanField(default=False, help_text='If true, this slot repeats weekly on the same day/time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.doctor')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['doctor', 'start_time'], name='core_doctor_doctor__1a0033_idx'), models.Index(fields=['start_time'], name='core_doctor_start_t_8ec963_idx')],
                'unique_together': {('doctor', 'start_time')},
            },
        ),
    ]
