# Generated by Django 5.1.15 on 2025-12-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.DateTimeField(editable=False, help_text='Automatically set to start_time + 30 minutes'),
        ),
    ]
