# Generated by Django 6.0 on 2025-12-21 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_doctoravailability_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_from_user', models.BooleanField(default=True, help_text='True if message is from the patient, False if from AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to='core.patient')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='core_aichat_patient_7f7717_idx')],
            },
        ),
    ]
