# Generated by Django 6.0 on 2025-12-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='recurrence_day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday ... 6=Sunday — only used if is_recurring=True', null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Optional: stop recurring after this date', null=True),
        ),
    ]
