# Generated by Django 6.0 on 2026-01-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuarance',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_logos/'),
        ),
    ]
