# Generated by Django 6.0 on 2026-01-13 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_insuarance_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['recurrence_day_of_week', 'start_time_of_day', 'specific_date']},
        ),
        migrations.RemoveIndex(
            model_name='doctoravailability',
            name='core_doctor_doctor__1a0033_idx',
        ),
        migrations.RemoveIndex(
            model_name='doctoravailability',
            name='core_doctor_start_t_8ec963_idx',
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_time_of_day',
            field=models.TimeField(default=datetime.time(18, 0), help_text='End time of day for recurring block (e.g., 17:00:00)'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='start_time_of_day',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Start time of day for recurring block (e.g., 09:00:00)'),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'is_recurring', 'recurrence_day_of_week', 'specific_date'), name='unique_availability_block_per_doctor'),
        ),
    ]
