# Generated by Django 5.1.15 on 2026-03-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapists/')),
                ('location', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=120)),
                ('town', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('full_bio', models.TextField(blank=True)),
                ('qualifications', models.JSONField(blank=True, default=list)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=80, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ManyToManyField(blank=True, related_name='therapists', to='core.specialty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TherapistReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.therapist')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
