# Generated by Django 5.1.15 on 2026-03-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_therapist_therapistreview'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aichatmessage',
            name='core_aichat_patient_7f7717_idx',
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='is_from_user',
            field=models.BooleanField(default=True, help_text='True if message is from the user, False if from AI'),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages_legacy', to='core.patient'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['user', 'created_at'], name='core_aichat_user_id_49f7ba_idx'),
        ),
    ]
