# Generated by Django 5.1.15 on 2026-03-13 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_aichatmessage_core_aichat_patient_7f7717_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='featured_banners/')),
                ('action_text', models.CharField(blank=True, help_text='e.g., Learn More, Start Now', max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='Internal route or external URL', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('display_from', models.DateTimeField(blank=True, null=True)),
                ('display_until', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Featured Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrisisHelpline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Kenya Red Cross, SAMH, 988 Lifeline', max_length=200)),
                ('phone_number', models.CharField(help_text='e.g., 1199, 988', max_length=50)),
                ('description', models.TextField(blank=True, help_text='What this helpline offers')),
                ('is_24_7', models.BooleanField(default=True, help_text='Available 24/7')),
                ('languages', models.CharField(blank=True, help_text='Comma-separated, e.g., English, Swahili', max_length=200)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary helpline for this country')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_helplines', to='core.country')),
            ],
            options={
                'ordering': ['country', '-is_primary', 'display_order'],
                'unique_together': {('country', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('REMINDER', 'Reminder'), ('APPOINTMENT', 'Appointment')], default='INFO', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='notifications-outline', max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='Where to navigate on tap', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_userno_user_id_de9aad_idx')],
            },
        ),
        migrations.CreateModel(
            name='WellnessArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(help_text='Short description', max_length=300)),
                ('category', models.CharField(choices=[('SELF_CARE', 'Self-Care'), ('RESEARCH', 'Research'), ('MINDFULNESS', 'Mindfulness'), ('THERAPY', 'Therapy'), ('STRESS', 'Stress Management'), ('RELATIONSHIPS', 'Relationships'), ('SLEEP', 'Sleep'), ('NUTRITION', 'Nutrition')], default='SELF_CARE', max_length=50)),
                ('icon', models.CharField(default='heart-outline', help_text='Ionicons name', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wellness_articles/')),
                ('content', models.TextField(blank=True, help_text='Full article content (optional)')),
                ('external_url', models.URLField(blank=True, help_text='Link to external article')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_featured', 'is_active', 'display_order'], name='core_wellne_is_feat_f6638f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WellnessTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Short, actionable wellness advice')),
                ('icon', models.CharField(default='bulb-outline', help_text='Ionicons name', max_length=50)),
                ('category', models.CharField(blank=True, help_text='e.g., Breathing, Meditation, Sleep', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('display_from', models.DateField(blank=True, help_text='Start showing from this date', null=True)),
                ('display_until', models.DateField(blank=True, help_text='Stop showing after this date', null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wellness_tips', to=settings.AUTH_USER_MODEL)),
                ('target_countries', models.ManyToManyField(blank=True, help_text='Leave empty for all countries', to='core.country')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_from', 'display_until'], name='core_wellne_is_acti_9cc79e_idx')],
            },
        ),
    ]
