# Generated by Django 5.1.15 on 2026-03-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_featuredbanner_crisishelpline_usernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredbanner',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wellnessarticle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wellnesstip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wellnesstip',
            name='target_countries',
        ),
        migrations.DeleteModel(
            name='CrisisHelpline',
        ),
        migrations.DeleteModel(
            name='FeaturedBanner',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
        migrations.DeleteModel(
            name='WellnessArticle',
        ),
        migrations.DeleteModel(
            name='WellnessTip',
        ),
    ]
